date = input("What day is it. ")
print("Good to know it's " + date)
holiday = input("Whats your favorite holiday ")
print("I didn't know you liked " + holiday)
print("Today is " + date + "and your favio es " + holiday) 